### ISSUE TITLE
Missing `pytorch-lightning` dependency in NVSR requirements

### ISSUE THREAD

**Issue by lmmx** [haoheliu/ssr_eval#2]
The `NVSR/nvsr_unet.py` module imports `pytorch_lightning` (line 10), but this isn't included in the `NVSR/requirements.txt` file (`pytorch-lightning`), just wanted to report while installing your package!

**Comment by haoheliu** [comment]
Many thanks @lmmx for reporting the bug. I've added the requirements to the file.
