### ISSUE TITLE
Use the pretrained model to predict 16 kHz track

### ISSUE THREAD

**Issue by ruizhecao96** [haoheliu/ssr_eval#3]
Hello,

Your work is awesome! Can I use the provided 48 kHz pretrained model to predict the 16 kHz track directly? e.g. 4 kHz to 16 kHz. Or do I need to retrain the model?

Best regards

**Comment by haoheliu** [comment]
@ruizhecao96 Thanks for your interest! Sure, you can predict the 16kHz track. The target sampling rate of the pre-trained NVSR model is 44.1kHz. You can first resample your input to 44.1kHz. Then use our model to perform super-resolution. And finally resample it back to 16kHz.

**Comment by ruizhecao96** [comment]
> @ruizhecao96 Thanks for your interest! Sure, you can predict the 16kHz track. The target sampling rate of the pre-trained NVSR model is 44.1kHz. You can first resample your input to 44.1kHz. Then use our model to perform super-resolution. And finally resample it back to 16kHz.

I am not sure if I get the point. For example, I have a 4 kHz audio and I want to upsample it to 16 kHz using pretrained NVSR. Do you mean I first upsample it to 44.1 kHz using NVSR and then resample it to 16 kHz?

**Comment by haoheliu** [comment]
> Do you mean I first upsample it to 44.1 kHz using NVSR and then resample it to 16 kHz?

Yes, that's right.

**Comment by ruizhecao96** [comment]
Thank you very much!
